- name: pre-required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - gnupg
    - python3-pip

- name: install/update pip packages
  pip:
    name: "{{ item }}"
    state: latest
    executable: pip3
  loop:
    - docker
    - jsondiff

- name: add docker repo key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add repository
  apt_repository:
    filename: docker
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: install/update docker package
  apt:
    name:
      - docker-ce={{ docker_version }}
      - docker-ce-cli={{ docker_version }}
      - containerd.io
    state: present
    update_cache: yes
  register: docker_engine_update

- name: login to docker registries
  docker_login:
    password: "{{ item.password }}"
    reauthorize: yes
    registry_url: "{{ item.registry }}"
    state: present
    username: "{{ item.user }}"
  with_items: "{{ docker_registry_accounts }}"
  no_log: yes
